"use client";

import { FormEvent, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const levels = ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"];
type Role = "student" | "teacher";
type ChatMessage = { role: "user" | "assistant"; content: string; sources: any[] };

export default function Workspace({ role }: { role: Role }) {
  const [token, setToken] = useState("");
  const [code, setCode] = useState("");
  const [text, setText] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [name, setName] = useState("study-notes");
  const [question, setQuestion] = useState("");
  const [scope, setScope] = useState<"public" | "protected">("public");
  const [result, setResult] = useState<any>();
  const [history, setHistory] = useState<ChatMessage[]>([]);
  const [busy, setBusy] = useState(false);
  const [busyLabel, setBusyLabel] = useState("");
  const [error, setError] = useState("");

  async function call(path: string, body: any) {
    const response = await fetch(API + path, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body) });
    const data = await response.json();
    if (!response.ok) throw Error(data.detail || "The local service could not complete this request.");
    return data;
  }
  function begin(label: string) { setBusyLabel(label); setBusy(true); setError(""); }
  function finish() { setBusy(false); setBusyLabel(""); }
  async function login(event: FormEvent) { event.preventDefault(); begin("Opening local workspace"); try { const data = await call("/auth/session", { role, access_code: code }); setToken(data.access_token); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function index() { begin("Indexing your material"); try { setResult(await call("/documents/index", { text, name, scope, content_type: scope === "protected" ? "exam_paper" : "study_material" })); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function upload() { if (!file) return; begin("Uploading and indexing your file"); try { const form = new FormData(); form.set("file", file); form.set("scope", scope); form.set("content_type", scope === "protected" ? "exam_paper" : "study_material"); const response = await fetch(API + "/documents/upload", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); const data = await response.json(); if (!response.ok) throw Error(data.detail || "Upload failed"); setResult(data); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function ask(summary = false) { const prompt = question.trim(); begin(summary ? "Preparing a local summary" : "Loading the local model and writing a reply"); try { const data = role === "student" ? await call("/chat", { question: prompt, scope, top_k: 4, summary, history: history.map(({ role, content }) => ({ role, content })) }) : await call(summary ? "/summarize" : "/qa", { question: prompt, scope, top_k: 4 }); setResult(data); if (role === "student") { setHistory((old) => [...old, { role: "user", content: prompt, sources: [] }, { role: "assistant", content: data.answer, sources: data.sources || [] }]); setQuestion(""); } } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function classify() { begin("Classifying the question"); try { setResult(await call(role === "teacher" ? "/teacher/exam/classify" : "/bloom/classify", { question })); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function moderate() { begin("Preparing moderation guidance"); try { setResult(await call("/teacher/exam/moderate", { question })); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }
  async function review(decision: "approved" | "needs_revision" | "rejected") { begin("Saving review"); try { const item = await call("/teacher/exam/review", { question, decision, notes: "" }); setResult((old: any) => ({ ...old, review: item })); } catch (e) { setError(String(e).replace("Error: ", "")); } finally { finish(); } }

  if (!token) return <main className="page-wrap fade-in"><section className="glass-card mx-auto max-w-md rounded-[28px] p-7 sm:p-9"><p className="eyebrow">Framework local workspace</p><h1 className="display mt-4 text-3xl font-extrabold capitalize">{role} access</h1><p className="section-copy">Enter the locally configured access code. This session stays on this computer.</p><form className="mt-7 grid gap-4" onSubmit={login}><label>Local access code<input value={code} onChange={(e) => setCode(e.target.value)} type="password" placeholder="Enter access code" /></label><button className="btn-primary" disabled={busy}>{busy ? "Opening workspace..." : "Open workspace"}</button></form>{error && <p className="mt-4 rounded-xl bg-red-50/70 p-3 text-sm text-[#a03d49]">{error}</p>}</section></main>;

  const bloom = result?.bloom || result;
  const active = levels.indexOf(bloom?.level || "");
  const materialWorking = busyLabel.includes("Uploading") || busyLabel.includes("Indexing");
  const materialReady = !busy && result?.indexed_chunks !== undefined;
  return <main className="page-wrap fade-in"><header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">{role === "teacher" ? "Protected moderation studio" : "Student learning studio"}</p><h1 className="display mt-3 text-4xl font-extrabold capitalize">{role} workspace</h1><p className="section-copy">{role === "teacher" ? "Moderate questions, work with authorized corpus material, and review Bloom alignment." : "Build understanding privately with a local model or your own material."}</p></div><div className="glass-pill w-fit rounded-full px-3 py-2"><span className={`status ${scope === "protected" ? "protected" : ""}`}>{scope === "protected" ? "Protected corpus" : "Local / offline"}</span></div></header>
    <div className="grid gap-5 lg:grid-cols-[.92fr_1.08fr]">
      <section className="glass-card lift rounded-[26px] p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><h2 className="section-title">Course material</h2><p className="section-copy">Index a file or paste text into your authorized local corpus.</p></div><span className="status">Private</span></div><div className="mt-6 grid gap-4"><label>Document name<input value={name} onChange={(e) => setName(e.target.value)} /></label>{role === "teacher" && <label>Corpus access<select value={scope} onChange={(e) => setScope(e.target.value as "public" | "protected")}><option value="public">Public learning corpus</option><option value="protected">Protected exam corpus</option></select></label>}<label className="glass-pill block rounded-2xl border-dashed p-5 text-center transition hover:bg-white/60"><span className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-[#e7efff] text-lg text-[#426bdc]">↑</span><span className="mt-3 block text-sm font-bold text-[#36577a]">{file ? file.name : "Choose a learning document"}</span><span className="mt-1 block text-xs font-medium text-[#718096]">PDF, image, TXT, or Markdown</span><input className="sr-only" type="file" accept=".pdf,.png,.jpg,.jpeg,.tif,.tiff,.bmp,.webp,.txt,.md" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><button className="btn-secondary" disabled={busy || !file} onClick={upload}>Upload and index file</button><div className="relative my-1 border-t border-white/70"><span className="absolute left-1/2 -translate-x-1/2 -translate-y-1/2 bg-[#e2eff8] px-2 text-[10px] font-bold uppercase tracking-widest text-[#718096]">or paste text</span></div><textarea className="min-h-32" value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste learning material to index..." /><button className="btn-primary" disabled={busy || !text.trim()} onClick={index}>Index pasted material</button>{(materialWorking || materialReady) && <div className={`material-progress ${materialWorking ? "is-working" : "is-complete"}`} role="status">{materialWorking ? <><span className="material-spinner" /><span><b>{busyLabel}</b><small>Preparing your material for source-grounded answers.</small></span></> : <><span className="material-check">✓</span><span><b>Material indexed</b><small>{result.indexed_chunks} chunk{result.indexed_chunks === 1 ? "" : "s"} are ready in this session.</small></span></>}</div>}</div></section>
      <section className={`glass-card lift rounded-[26px] p-5 sm:p-7 ${role === "student" ? "student-chat-card" : ""}`}><div className="flex items-start justify-between gap-3"><div><h2 className="section-title">{role === "teacher" ? "Question moderation" : "Ask anything"}</h2><p className="section-copy">{role === "teacher" ? "Classify cognitive demand and develop a higher-level revision." : "Continue a private local conversation, or upload material when you want source-grounded answers."}</p></div><span className="status">CPU ready</span></div>{role === "student" && <div className="student-chat-thread" aria-live="polite">{history.length === 0 ? <p className="student-chat-empty">Your local conversations stay in this session.</p> : history.map((message, index) => <article key={index} className={`student-message ${message.role}`}><p className="student-message-label">{message.role === "user" ? "You" : "Assistant"}</p><p className="student-message-content">{message.content}</p>{message.role === "assistant" && message.sources.length > 0 && <p className="student-message-sources">{message.sources.length} authorized source{message.sources.length === 1 ? "" : "s"} used</p>}</article>)}{busy && !materialWorking && <article className="student-message assistant student-message-loading"><p className="student-message-label">Assistant</p><span className="typing-dots" aria-label="Loading"><i /><i /><i /></span></article>}</div>}<div className="mt-6 grid gap-4">{role === "teacher" && <label>Retrieval scope<select value={scope} onChange={(e) => setScope(e.target.value as "public" | "protected")}><option value="public">Public learning corpus</option><option value="protected">Protected exam corpus</option></select></label>}<label>{role === "teacher" ? "Exam or practice question" : "Question or text to summarize"}<textarea className="mt-1 min-h-32" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder={role === "teacher" ? "Paste a question for Bloom moderation..." : "Ask a question or paste text to summarize..."} /></label><div className="flex flex-wrap gap-2"><button className="btn-primary" disabled={busy || !question.trim()} onClick={() => ask(false)}>{role === "student" ? "Send" : "Answer with sources"}</button><button className="btn-secondary" disabled={busy || !question.trim()} onClick={() => ask(true)}>Summarize</button>{role === "teacher" && <><button className="btn-secondary" disabled={busy || !question.trim()} onClick={classify}>Classify level</button><button className="btn-primary" disabled={busy || !question.trim()} onClick={moderate}>Moderate & rewrite</button></>}</div></div></section>
    </div>{error && <section className="glass-card mt-5 rounded-[22px] border border-red-200/80 bg-red-50/40 p-5" role="alert"><p className="font-bold text-[#9f3e48]">Local model or request unavailable</p><p className="mt-1 text-sm leading-6 text-[#9f3e48]">{error}</p></section>}{role === "teacher" && result && <section className="glass-card mt-5 rounded-[26px] p-5 sm:p-7"><h2 className="section-title">{result.moderation ? "Moderation review" : result.answer ? "Grounded answer" : "Response"}</h2>{bloom?.level && <div className="glass-pill mt-5 rounded-2xl p-4"><p className="font-extrabold text-[#294f7b]">{bloom.level} Bloom level</p><div className="mt-4 grid grid-cols-6 gap-1.5">{levels.map((level, index) => <div key={level}><div className={`bloom-step ${index <= active ? "active" : ""}`} /><span className="mt-1 block truncate text-[9px] font-bold text-[#718096]">{level}</span></div>)}</div></div>}{result.answer && <p className="mt-6 whitespace-pre-wrap leading-8 text-[#26364e]">{result.answer}</p>}{result.moderation && <div className="mt-6 grid gap-4"><article className="glass-pill rounded-2xl p-5"><p className="eyebrow">Moderation rationale</p><p className="mt-3 text-sm leading-7 text-[#30435f]">{result.moderation.reason}</p></article><article className="glass-pill rounded-2xl p-5"><p className="eyebrow">Higher-level rewrite</p><p className="mt-3 text-sm font-semibold leading-7 text-[#30435f]">{result.moderation.higher_level_rewrite}</p></article><div className="flex flex-wrap gap-2"><button className="btn-primary" onClick={() => review("approved")}>Approve</button><button className="btn-secondary" onClick={() => review("needs_revision")}>Needs revision</button><button className="btn-quiet" onClick={() => review("rejected")}>Reject</button></div></div>}</section>}</main>;
}
